name: Pipeline CI CD
on: 
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Hello World Action
            run: echo "Hello, world!"
          - name: Checkout repository
            uses: actions/checkout@v2
          - name: Install npm dependencies
            run: npm install
          - name: Run tests
            run: npm test
